name: Metrics
on:
  # Schedule updates (every 24 hours)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually from the Actions tab
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: IJSK10
          template: classic
          base: header, repositories
          config_timezone: America/New_York
          
          # üó£Ô∏è Languages Configuration
          plugin_languages: yes
          # This removes Jupyter Notebooks, HTML, and CSS from the stats
          plugin_languages_ignored: html, css, jupyter notebook
          plugin_languages_limit: 8
          
          # üß† LeetCode Configuration
          plugin_leetcode: yes
          # I used user2870Yt because that is what was in your profile link
          plugin_leetcode_user: user2870Yt
          plugin_leetcode_sections: solved, skills, recent
