name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. Your existing GitHub Stats Step
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: IJSK10
          template: classic
          base: header, repositories
          config_timezone: America/New_York
          plugin_languages: yes
          plugin_languages_ignored: html, css, jupyter notebook
          plugin_languages_limit: 8

      - name: LeetCode
        uses: lowlighter/metrics@latest
        with:
          filename: leetcode.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_user: user2870Yt
          plugin_leetcode_sections: solved, skills, recent
